//
// This file was generated by the JPA Modeler
//
package org.op.data.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToOne;

@Entity

public class Subscription extends Activity implements Serializable
{

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Basic
    private String commentsByContact;

    @OneToOne(optional = true, targetEntity = Contact.class)
    private Contact contact;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Basic
    private boolean present;



    public Subscription()
    {

    }



    public String getCommentsByContact()
    {
        return this.commentsByContact;
    }



    public void setCommentsByContact(String commentsByContact)
    {
        this.commentsByContact = commentsByContact;
    }



    public Contact getContact()
    {
        return this.contact;
    }



    public void setContact(Contact contact)
    {
        this.contact = contact;
    }



    public boolean isPresent()
    {
        return this.present;
    }



    public void setPresent(boolean present)
    {
        this.present = present;
    }
}
